"""Add Attempt Duration Field

Revision ID: 438dfb54d7b8
Revises: d32c14d3b045
Create Date: 2025-05-25 15:39:04.313200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438dfb54d7b8'
down_revision: Union[str, None] = 'd32c14d3b045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('attempt_duration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'attempt_duration')
    # ### end Alembic commands ###
