"""Added Hashed Password Col

Revision ID: 86d3011d92fa
Revises: 1f657cf03570
Create Date: 2025-06-24 09:10:45.932670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d3011d92fa'
down_revision: Union[str, None] = '1f657cf03570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_constraint('users_id_number_key', 'users', type_='unique')
    op.drop_column('users', 'id_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_id_number_key', 'users', ['id_number'])
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
